In [1]:
library(tidyverse)
library(skimr)
library(janitor)

-- Attaching packages ------------------------------------------------------------------------------- tidyverse 1.3.1 --

v ggplot2 3.3.5     v purrr   0.3.4
v tibble  3.1.5     v dplyr   1.0.7
v tidyr   1.1.4     v stringr 1.4.0
v readr   2.0.2     v forcats 0.5.1

-- Conflicts ---------------------------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()


Attachement du package : 'janitor'


Les objets suivants sont masqu√©s depuis 'package:stats':

    chisq.test, fisher.test

In [2]:
hotel_bookings <- read_csv("hotel_bookings.csv")

Rows: 119390 Columns: 32

-- Column specification ------------------------------------------------------------------------------------------------
Delimiter: ","
chr  (13): hotel, arrival_date_month, meal, country, market_segment, distrib...
dbl  (18): is_canceled, lead_time, arrival_date_year, arrival_date_week_numb...
date  (1): reservation_status_date


i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
str(hotel_bookings)

spec_tbl_df [119,390 x 32] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ hotel                         : chr [1:119390] "Resort Hotel" "Resort Hotel" "Resort Hotel" "Resort Hotel" ...
 $ is_canceled                   : num [1:119390] 0 0 0 0 0 0 0 0 1 1 ...
 $ lead_time                     : num [1:119390] 342 737 7 13 14 14 0 9 85 75 ...
 $ arrival_date_year             : num [1:119390] 2015 2015 2015 2015 2015 ...
 $ arrival_date_month            : chr [1:119390] "July" "July" "July" "July" ...
 $ arrival_date_week_number      : num [1:119390] 27 27 27 27 27 27 27 27 27 27 ...
 $ arrival_date_day_of_month     : num [1:119390] 1 1 1 1 1 1 1 1 1 1 ...
 $ stays_in_weekend_nights       : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ stays_in_week_nights          : num [1:119390] 0 0 1 1 2 2 2 2 3 3 ...
 $ adults                        : num [1:119390] 2 2 1 1 2 2 2 2 2 2 ...
 $ children                      : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ babies                        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ meal                          : chr [1:119390] "BB" "BB" "BB" "BB" ...
 $ country                       : chr [1:119390] "PRT" "PRT" "GBR" "GBR" ...
 $ market_segment                : chr [1:119390] "Direct" "Direct" "Direct" "Corporate" ...
 $ distribution_channel          : chr [1:119390] "Direct" "Direct" "Direct" "Corporate" ...
 $ is_repeated_guest             : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ previous_cancellations        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ previous_bookings_not_canceled: num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ reserved_room_type            : chr [1:119390] "C" "C" "A" "A" ...
 $ assigned_room_type            : chr [1:119390] "C" "C" "C" "A" ...
 $ booking_changes               : num [1:119390] 3 4 0 0 0 0 0 0 0 0 ...
 $ deposit_type                  : chr [1:119390] "No Deposit" "No Deposit" "No Deposit" "No Deposit" ...
 $ agent                         : chr [1:119390] "NULL" "NULL" "NULL" "304" ...
 $ company                       : chr [1:119390] "NULL" "NULL" "NULL" "NULL" ...
 $ days_in_waiting_list          : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ customer_type                 : chr [1:119390] "Transient" "Transient" "Transient" "Transient" ...
 $ adr                           : num [1:119390] 0 0 75 75 98 ...
 $ required_car_parking_spaces   : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...
 $ total_of_special_requests     : num [1:119390] 0 0 0 0 1 1 0 1 1 0 ...
 $ reservation_status            : chr [1:119390] "Check-Out" "Check-Out" "Check-Out" "Check-Out" ...
 $ reservation_status_date       : Date[1:119390], format: "2015-07-01" "2015-07-01" ...
 - attr(*, "spec")=
  .. cols(
  ..   hotel = col_character(),
  ..   is_canceled = col_double(),
  ..   lead_time = col_double(),
  ..   arrival_date_year = col_double(),
  ..   arrival_date_month = col_character(),
  ..   arrival_date_week_number = col_double(),
  ..   arrival_date_day_of_month = col_double(),
  ..   stays_in_weekend_nights = col_double(),
  ..   stays_in_week_nights = col_double(),
  ..   adults = col_double(),
  ..   children = col_double(),
  ..   babies = col_double(),
  ..   meal = col_character(),
  ..   country = col_character(),
  ..   market_segment = col_character(),
  ..   distribution_channel = col_character(),
  ..   is_repeated_guest = col_double(),
  ..   previous_cancellations = col_double(),
  ..   previous_bookings_not_canceled = col_double(),
  ..   reserved_room_type = col_character(),
  ..   assigned_room_type = col_character(),
  ..   booking_changes = col_double(),
  ..   deposit_type = col_character(),
  ..   agent = col_character(),
  ..   company = col_character(),
  ..   days_in_waiting_list = col_double(),
  ..   customer_type = col_character(),
  ..   adr = col_double(),
  ..   required_car_parking_spaces = col_double(),
  ..   total_of_special_requests = col_double(),
  ..   reservation_status = col_character(),
  ..   reservation_status_date = col_date(format = "")
  .. )
 - attr(*, "problems")=<externalptr>

In [5]:
glimpse(hotel_bookings)

Rows: 119,390
Columns: 32
$ hotel                          <chr> "Resort Hotel", "Resort Hotel", "Resort~
$ is_canceled                    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, ~
$ lead_time                      <dbl> 342, 737, 7, 13, 14, 14, 0, 9, 85, 75, ~
$ arrival_date_year              <dbl> 2015, 2015, 2015, 2015, 2015, 2015, 201~
$ arrival_date_month             <chr> "July", "July", "July", "July", "July",~
$ arrival_date_week_number       <dbl> 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,~
$ arrival_date_day_of_month      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ~
$ stays_in_weekend_nights        <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ stays_in_week_nights           <dbl> 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, ~
$ adults                         <dbl> 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, ~
$ children                       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ babies                         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ meal                           <chr> "BB", "BB", "BB", "BB", "BB", "BB", "BB~
$ country                        <chr> "PRT", "PRT", "GBR", "GBR", "GBR", "GBR~
$ market_segment                 <chr> "Direct", "Direct", "Direct", "Corporat~
$ distribution_channel           <chr> "Direct", "Direct", "Direct", "Corporat~
$ is_repeated_guest              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ previous_cancellations         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ previous_bookings_not_canceled <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ reserved_room_type             <chr> "C", "C", "A", "A", "A", "A", "C", "C",~
$ assigned_room_type             <chr> "C", "C", "C", "A", "A", "A", "C", "C",~
$ booking_changes                <dbl> 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ deposit_type                   <chr> "No Deposit", "No Deposit", "No Deposit~
$ agent                          <chr> "NULL", "NULL", "NULL", "304", "240", "~
$ company                        <chr> "NULL", "NULL", "NULL", "NULL", "NULL",~
$ days_in_waiting_list           <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ customer_type                  <chr> "Transient", "Transient", "Transient", ~
$ adr                            <dbl> 0.00, 0.00, 75.00, 75.00, 98.00, 98.00,~
$ required_car_parking_spaces    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
$ total_of_special_requests      <dbl> 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 3, ~
$ reservation_status             <chr> "Check-Out", "Check-Out", "Check-Out", ~
$ reservation_status_date        <date> 2015-07-01, 2015-07-01, 2015-07-02, 20~

In [7]:
head(hotel_bookings['arrival_date_month'])

  arrival_date_month
1 July
2 July
3 July
4 July
5 July
6 July

In [10]:
colnames(hotel_bookings)

[1] "hotel"                    "is_canceled"
[3] "lead_time"                "arrival_date_year"
[5] "arrival_date_month"       "arrival_date_week_number"

In [11]:
head(arrange(hotel_bookings))

  hotel        is_canceled lead_time arrival_date_year arrival_date_month
1 Resort Hotel 0           342       2015              July
2 Resort Hotel 0           737       2015              July
3 Resort Hotel 0             7       2015              July
4 Resort Hotel 0            13       2015              July
5 Resort Hotel 0            14       2015              July
6 Resort Hotel 0            14       2015              July
  arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights
1 27                       1                         0
2 27                       1                         0
3 27                       1                         0
4 27                       1                         0
5 27                       1                         0
6 27                       1                         0
  stays_in_week_nights adults ... deposit_type agent company
1 0                    2      ... No Deposit   NULL  NULL
2 0                    2      ... No Deposit   NULL  NULL
3 1                    1      ... No Deposit   NULL  NULL
4 1                    1      ... No Deposit   304   NULL
5 2                    2      ... No Deposit   240   NULL
6 2                    2      ... No Deposit   240   NULL
  days_in_waiting_list customer_type adr required_car_parking_spaces
1 0                    Transient      0  0
2 0                    Transient      0  0
3 0                    Transient     75  0
4 0                    Transient     75  0
5 0                    Transient     98  0
6 0                    Transient     98  0
  total_of_special_requests reservation_status reservation_status_date
1 0                         Check-Out          2015-07-01
2 0                         Check-Out          2015-07-01
3 0                         Check-Out          2015-07-02
4 0                         Check-Out          2015-07-02
5 1                         Check-Out          2015-07-03
6 1                         Check-Out          2015-07-03

In [16]:
head(hotel_bookings) %>% arrange(-lead_time)

  hotel        is_canceled lead_time arrival_date_year arrival_date_month
1 Resort Hotel 0           737       2015              July
2 Resort Hotel 0           342       2015              July
3 Resort Hotel 0            14       2015              July
4 Resort Hotel 0            14       2015              July
5 Resort Hotel 0            13       2015              July
6 Resort Hotel 0             7       2015              July
  arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights
1 27                       1                         0
2 27                       1                         0
3 27                       1                         0
4 27                       1                         0
5 27                       1                         0
6 27                       1                         0
  stays_in_week_nights adults ... deposit_type agent company
1 0                    2      ... No Deposit   NULL  NULL
2 0                    2      ... No Deposit   NULL  NULL
3 2                    2      ... No Deposit   240   NULL
4 2                    2      ... No Deposit   240   NULL
5 1                    1      ... No Deposit   304   NULL
6 1                    1      ... No Deposit   NULL  NULL
  days_in_waiting_list customer_type adr required_car_parking_spaces
1 0                    Transient      0  0
2 0                    Transient      0  0
3 0                    Transient     98  0
4 0                    Transient     98  0
5 0                    Transient     75  0
6 0                    Transient     75  0
  total_of_special_requests reservation_status reservation_status_date
1 0                         Check-Out          2015-07-01
2 0                         Check-Out          2015-07-01
3 1                         Check-Out          2015-07-03
4 1                         Check-Out          2015-07-03
5 0                         Check-Out          2015-07-02
6 0                         Check-Out          2015-07-02

**Max($) :** Finds directly the max data for a specific column

In [18]:
max(hotel_bookings$lead_time)

[1] 737

**Min($) :** Finds directly the min data for a specific column

In [20]:
min(hotel_bookings$lead_time)

[1] 0

**Mean($) :** Finds directly the mean data for a specific column

In [22]:
mean(hotel_bookings$lead_time)

[1] 104.0114

**Filter($) :** Filter out the dataframe following a specific condition

In [23]:
filter(hotel_bookings, hotel_bookings$hotel=="City Hotel")

      hotel      is_canceled lead_time arrival_date_year arrival_date_month
1     City Hotel 0             6       2015              July
2     City Hotel 1            88       2015              July
3     City Hotel 1            65       2015              July
4     City Hotel 1            92       2015              July
5     City Hotel 1           100       2015              July
6     City Hotel 1            79       2015              July
7     City Hotel 0             3       2015              July
8     City Hotel 1            63       2015              July
9     City Hotel 1            62       2015              July
10    City Hotel 1            62       2015              July
11    City Hotel 0            43       2015              July
12    City Hotel 0            43       2015              July
13    City Hotel 0            43       2015              July
14    City Hotel 0             4       2015              July
15    City Hotel 1            43       2015              July
16    City Hotel 0            43       2015              July
17    City Hotel 1            43       2015              July
18    City Hotel 0            43       2015              July
19    City Hotel 0            43       2015              July
20    City Hotel 1            43       2015              July
21    City Hotel 1            43       2015              July
22    City Hotel 1            97       2015              July
23    City Hotel 0            43       2015              July
24    City Hotel 0            43       2015              July
25    City Hotel 1            80       2015              July
26    City Hotel 0            60       2015              July
27    City Hotel 1           106       2015              July
28    City Hotel 1            68       2015              July
29    City Hotel 1            92       2015              July
30    City Hotel 0            18       2015              July
...   ...        ...         ...       ...               ...
79301 City Hotel 0           195       2017              August
79302 City Hotel 0           100       2017              August
79303 City Hotel 0           198       2017              August
79304 City Hotel 0           212       2017              August
79305 City Hotel 0           212       2017              August
79306 City Hotel 0            54       2017              August
79307 City Hotel 0           210       2017              August
79308 City Hotel 0           212       2017              August
79309 City Hotel 0           261       2017              August
79310 City Hotel 0           207       2017              August
79311 City Hotel 0           201       2017              August
79312 City Hotel 0           175       2017              August
79313 City Hotel 0           175       2017              August
79314 City Hotel 0           175       2017              August
79315 City Hotel 0           201       2017              August
79316 City Hotel 0           200       2017              August
79317 City Hotel 0           165       2017              August
79318 City Hotel 0           185       2017              August
79319 City Hotel 0           247       2017              August
79320 City Hotel 0           109       2017              August
79321 City Hotel 0            44       2017              August
79322 City Hotel 0           188       2017              August
79323 City Hotel 0           135       2017              August
79324 City Hotel 0           164       2017              August
79325 City Hotel 0            21       2017              August
79326 City Hotel 0            23       2017              August
79327 City Hotel 0           102       2017              August
79328 City Hotel 0            34       2017              August
79329 City Hotel 0           109       2017              August
79330 City Hotel 0           205       2017              August
      arrival_date_week_number arrival_date_day_of_month
1     27                       1
2     27                       1
3     27                       1
4     27                       1
5     27                       2
6     27                       2
7     27                       2
8     27                       2
9     27                       2
10    27                       2
11    27                       3
12    27                       3
13    27                       3
14    27                       3
15    27                       3
16    27                       3
17    27                       3
18    27                       3
19    27                       3
20    27                       3
21    27                       3
22    27                       3
23    27                       3
24    27                       3
25    27                       3
26    27                       3
27    27                       4
28    27                       4
29    27                       4
30    27                       4
...   ...                      ...
79301 35                       29
79302 35                       31
79303 35                       29
79304 35                       28
79305 35                       28
79306 35                       27
79307 35                       28
79308 35                       28
79309 35                       30
79310 34                       25
79311 35                       30
79312 35                       31
79313 35                       31
79314 35                       31
79315 35                       29
79316 35                       30
79317 35                       29
79318 35                       30
79319 35                       31
79320 35                       31
79321 35                       31
79322 35                       31
79323 35                       30
79324 35                       31
79325 35                       30
79326 35                       30
79327 35                       31
79328 35                       31
79329 35                       31
79330 35                       29
      stays_in_weekend_nights stays_in_week_nights adults ... deposit_type
1     0                       2                    1      ... No Deposit
2     0                       4                    2      ... No Deposit
3     0                       4                    1      ... No Deposit
4     2                       4                    2      ... No Deposit
5     0                       2                    2      ... No Deposit
6     0                       3                    2      ... No Deposit
7     0                       3                    1      ... No Deposit
8     1                       3                    1      ... No Deposit
9     2                       3                    2      ... No Deposit
10    2                       3                    2      ... No Deposit
11    0                       2                    2      ... No Deposit
12    0                       2                    2      ... No Deposit
13    0                       2                    2      ... No Deposit
14    0                       2                    1      ... No Deposit
15    0                       2                    2      ... No Deposit
16    0                       2                    1      ... No Deposit
17    0                       2                    1      ... No Deposit
18    0                       2                    2      ... No Deposit
19    0                       2                    2      ... No Deposit
20    0                       2                    1      ... No Deposit
21    0                       2                    2      ... No Deposit
22    0                       2                    2      ... No Deposit
23    0                       2                    2      ... No Deposit
24    0                       2                    2      ... No Deposit
25    1                       2                    2      ... No Deposit
26    2                       5                    2      ... No Deposit
27    1                       1                    1      ... No Deposit
28    2                       1                    1      ... No Deposit
29    2                       1                    2      ... No Deposit
30    2                       2                    1      ... No Deposit
...   ...                     ...                  ...        ...
79301 1                       5                    2      ... No Deposit
79302 1                       3                    2      ... No Deposit
79303 1                       5                    2      ... No Deposit
79304 2                       5                    2      ... No Deposit
79305 2                       5                    2      ... No Deposit
79306 3                       5                    1      ... No Deposit
79307 2                       5                    2      ... No Deposit
79308 2                       5                    2      ... No Deposit
79309 1                       4                    2      ... No Deposit
79310 3                       7                    2      ... No Deposit
79311 1                       4                    1      ... No Deposit
79312 1                       3                    2      ... No Deposit
79313 1                       3                    1      ... No Deposit
79314 1                       3                    1      ... No Deposit
79315 1                       5                    2      ... No Deposit
79316 1                       4                    2      ... No Deposit
79317 1                       5                    3      ... No Deposit
79318 1                       4                    2      ... No Deposit
79319 1                       3                    2      ... No Deposit
79320 1                       3                    2      ... No Deposit
79321 1                       3                    2      ... No Deposit
79322 2                       3                    2      ... No Deposit
79323 2                       4                    3      ... No Deposit
79324 2                       4                    2      ... No Deposit
79325 2                       5                    2      ... No Deposit
79326 2                       5                    2      ... No Deposit
79327 2                       5                    3      ... No Deposit
79328 2                       5                    2      ... No Deposit
79329 2                       5                    2      ... No Deposit
79330 2                       7                    2      ... No Deposit
      agent company days_in_waiting_list customer_type   adr
1     6     NULL    0                    Transient        0.00
2     9     NULL    0                    Transient       76.50
3     9     NULL    0                    Transient       68.00
4     9     NULL    0                    Transient       76.50
5     9     NULL    0                    Transient       76.50
6     9     NULL    0                    Transient       76.50
7     1     NULL    0                    Transient-Party 58.67
8     9     NULL    0                    Transient       68.00
9     8     NULL    0                    Transient       76.50
10    8     NULL    0                    Transient       76.50
11    1     NULL    0                    Transient-Party 86.00
12    1     NULL    0                    Transient-Party 43.00
13    1     NULL    0                    Transient-Party 86.00
14    1     NULL    0                    Transient-Party 63.00
15    1     NULL    0                    Transient-Party 86.00
16    1     NULL    0                    Transient-Party 63.00
17    1     NULL    0                    Transient-Party 63.00
18    1     NULL    0                    Transient-Party 86.00
19    1     NULL    0                    Transient-Party 86.00
20    1     NULL    0                    Transient-Party 63.00
21    1     NULL    0                    Transient-Party 86.00
22    13    NULL    0                    Transient       63.75
23    1     NULL    0                    Transient-Party 86.00
24    1     NULL    0                    Transient-Party 86.00
25    9     NULL    0                    Transient       76.50
26    11    NULL    0                    Transient       60.27
27    9     NULL    0                    Transient       68.00
28    9     NULL    0                    Transient       68.00
29    9     NULL    0                    Transient       76.50
30    1     NULL    0                    Transient-Party 60.00
...   ...   ...     ...                  ...             ...
79301 9     NULL    0                    Transient       117.00
79302 16    NULL    0                    Transient        95.85
79303 9     NULL    0                    Transient       119.17
79304 7     NULL    0                    Transient        92.17
79305 7     NULL    0                    Transient        92.17
79306 14    NULL    0                    Transient       266.75
79307 7     NULL    0                    Transient        85.59
79308 7     NULL    0                    Transient        85.59
79309 14    NULL    0                    Transient        99.00
79310 14    NULL    0                    Transient        96.25
79311 9     NULL    0                    Transient       108.00
79312 42    NULL    0                    Transient        86.85
79313 42    NULL    0                    Transient        82.35
79314 42    NULL    0                    Transient        82.35
79315 9     NULL    0                    Transient       117.00
79316 16    NULL    0                    Transient        85.50
79317 9     NULL    0                    Transient       209.25
79318 9     NULL    0                    Transient        99.00
79319 42    NULL    0                    Transient        86.85
79320 9     NULL    0                    Transient       155.00
79321 9     NULL    0                    Transient       140.75
79322 14    NULL    0                    Transient        99.00
79323 7     NULL    0                    Transient       209.00
79324 42    NULL    0                    Transient        87.60
79325 394   NULL    0                    Transient        96.14
79326 394   NULL    0                    Transient        96.14
79327 9     NULL    0                    Transient       225.43
79328 9     NULL    0                    Transient       157.71
79329 89    NULL    0                    Transient       104.40
79330 9     NULL    0                    Transient       151.20
      required_car_parking_spaces total_of_special_requests reservation_status
1     0                           0                         Check-Out
2     0                           1                         Canceled
3     0                           1                         Canceled
4     0                           2                         Canceled
5     0                           1                         Canceled
6     0                           1                         Canceled
7     0                           0                         Check-Out
8     0                           0                         Canceled
9     0                           1                         No-Show
10    0                           1                         No-Show
11    0                           0                         Check-Out
12    0                           0                         Check-Out
13    0                           0                         Check-Out
14    0                           0                         Check-Out
15    0                           0                         Canceled
16    0                           0                         Check-Out
17    0                           0                         Canceled
18    0                           0                         Check-Out
19    0                           0                         Check-Out
20    0                           0                         Canceled
21    0                           0                         Canceled
22    0                           1                         Canceled
23    0                           0                         Check-Out
24    0                           0                         Check-Out
25    0                           1                         Canceled
26    0                           0                         Check-Out
27    0                           0                         Canceled
28    0                           0                         Canceled
29    0                           1                         Canceled
30    0                           0                         Check-Out
...   ...                         ...                       ...
79301 0                           1                         Check-Out
79302 0                           0                         Check-Out
79303 0                           2                         Check-Out
79304 0                           1                         Check-Out
79305 0                           2                         Check-Out
79306 0                           1                         Check-Out
79307 0                           1                         Check-Out
79308 0                           0                         Check-Out
79309 0                           0                         Check-Out
79310 0                           2                         Check-Out
79311 0                           2                         Check-Out
79312 0                           2                         Check-Out
79313 0                           1                         Check-Out
79314 0                           1                         Check-Out
79315 0                           2                         Check-Out
79316 0                           1                         Check-Out
79317 0                           3                         Check-Out
79318 0                           1                         Check-Out
79319 0                           0                         Check-Out
79320 0                           1                         Check-Out
79321 0                           1                         Check-Out
79322 0                           0                         Check-Out
79323 0                           0                         Check-Out
79324 0                           0                         Check-Out
79325 0                           2                         Check-Out
79326 0                           0                         Check-Out
79327 0                           2                         Check-Out
79328 0                           4                         Check-Out
79329 0                           0                         Check-Out
79330 0                           2                         Check-Out
      reservation_status_date
1     2015-07-03
2     2015-07-01
3     2015-04-30
4     2015-06-23
5     2015-04-02
6     2015-06-25
7     2015-07-05
8     2015-06-25
9     2015-07-02
10    2015-07-02
11    2015-07-05
12    2015-07-05
13    2015-07-05
14    2015-07-05
15    2015-06-29
16    2015-07-05
17    2015-06-16
18    2015-07-05
19    2015-07-05
20    2015-06-29
21    2015-06-16
22    2015-06-30
23    2015-07-05
24    2015-07-05
25    2015-04-17
26    2015-07-10
27    2015-06-01
28    2015-06-23
29    2015-06-15
30    2015-07-08
...   ...
79301 2017-09-04
79302 2017-09-04
79303 2017-09-04
79304 2017-09-04
79305 2017-09-04
79306 2017-09-04
79307 2017-09-04
79308 2017-09-04
79309 2017-09-04
79310 2017-09-04
79311 2017-09-04
79312 2017-09-04
79313 2017-09-04
79314 2017-09-04
79315 2017-09-04
79316 2017-09-04
79317 2017-09-04
79318 2017-09-04
79319 2017-09-04
79320 2017-09-04
79321 2017-09-04
79322 2017-09-05
79323 2017-09-05
79324 2017-09-06
79325 2017-09-06
79326 2017-09-06
79327 2017-09-07
79328 2017-09-07
79329 2017-09-07
79330 2017-09-07

* Hotel summary

In [27]:
hotel_summary <- hotel_bookings %>% group_by(hotel) %>% summarize(average_lead_time = mean(lead_time),min_lead=min(lead_time),max_lead = (max(lead_time)))

In [28]:
hotel_summary

  hotel        average_lead_time min_lead max_lead
1 City Hotel   109.73572         0        629
2 Resort Hotel  92.67569         0        737